version: '3.5'
services:
  portfolio-be:
    build:
      context: .
    image: mbnatafgi/portfolio:be
    container_name: portfolio-be
    ports:
    - 8000:8000
    restart: always
  portfolio-nginx:
    build:
      context: ./nginx
    image: mbnatafgi/portfolio:nginx
    container_name: portfolio-nginx
    ports:
    - 80:80
    - 443:443
    volumes:
      - portfolio-fe:/portfolio-fe
      - portfolio-nginx:/portfolio-nginx
    restart: always
    depends_on:
      - portfolio-be
    env_file:
      - ./variables.env
  portfolio-jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: mbnatafgi/portfolio:jenkins
    container_name: portfolio-jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portfolio-fe:
    external: true
  portfolio-nginx:
    external: true
  jenkins_home:
    external: false
networks:
  default:
    external:
      name: portfolio